spring.application.name=email-writer-db

gemini.api.url=https://generativelanguage.googleapis.com
gemini.api.key=AIzaSyDrjM7CCqONUWFr4jdgfCwt77yZsJQ0wR8

//AIzaSyDrjM7CCqONUWFr4jdgfCwt77yZsJQ0wR8




